import AppKit
import MultipasteCore

/// Polls `NSPasteboard.general.changeCount` and snapshots its contents into
/// the history store whenever the count advances.
///
/// macOS does not deliver KVO/notification for pasteboard mutations, so a
/// short interval poll is the canonical approach (this is what every macOS
/// clipboard manager does — Maccy, Paste, Alfred, etc.). 300ms strikes a
/// balance between snappy capture and near-zero CPU at idle.
final class ClipboardMonitor {

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: DispatchSourceTimer?
    private let store: HistoryStore
    private let prefs: Preferences

    /// When true, the monitor still tracks `changeCount` (so it doesn't
    /// double-fire on resume) but skips inserting into history.
    var paused: Bool = false

    init(store: HistoryStore, prefs: Preferences) {
        self.store = store
        self.prefs = prefs
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        let t = DispatchSource.makeTimerSource(queue: .main)
        t.schedule(deadline: .now() + .milliseconds(300), repeating: .milliseconds(300))
        t.setEventHandler { [weak self] in self?.poll() }
        t.resume()
        timer = t
    }

    func stop() {
        timer?.cancel()
        timer = nil
    }

    private func poll() {
        let cc = pasteboard.changeCount
        guard cc != lastChangeCount else { return }
        lastChangeCount = cc
        guard !paused else { return }
        guard let item = snapshot() else { return }
        store.insert(item)
        augmentFileURLsIfNeeded(item: item)
    }

    /// When the user copies a file in Finder, the pasteboard carries
    /// `public.file-url` (and a few legacy URL types) but NO
    /// `public.utf8-plain-text`. Pasting into a code editor / terminal /
    /// search field therefore yields nothing useful — or, depending on
    /// the receiver's fallback logic, just the filename.
    ///
    /// We inject the full path as the `.string` representation while
    /// preserving every other type. Receivers pick whichever type they
    /// want:
    ///
    ///   - text controls (code tab) → string → path
    ///   - drop targets (chat tab) → file-url → the file itself
    ///
    /// Disabled via Preferences if a user prefers the old behavior.
    private func augmentFileURLsIfNeeded(item: ClipboardItem) {
        guard prefs.augmentFileCopiesWithPath else { return }
        guard case .fileURLs(let urls) = item.kind, !urls.isEmpty else { return }

        let existing = pasteboard.string(forType: .string)
        guard PasteboardAugmenter.shouldAugment(existing: existing) else { return }

        let pathText = PasteboardAugmenter.pathText(forFiles: urls)
        rewritePreservingTypes(addingString: pathText)
        // We just bumped changeCount; mark it as "ours" so our next poll
        // doesn't see this as a brand-new clipboard event.
        lastChangeCount = pasteboard.changeCount
    }

    /// Snapshot every existing type's data, clear the pasteboard, then
    /// re-declare all original types PLUS `.string` and write the data
    /// back. This is the only way to add a representation on top of an
    /// Apple-owned pasteboard (e.g. one set by Finder) without losing
    /// the original types — `addTypes(_:owner:)` requires us to be the
    /// pasteboard owner, which we aren't.
    private func rewritePreservingTypes(addingString string: String) {
        let originalTypes = pasteboard.types ?? []
        var saved: [(NSPasteboard.PasteboardType, Data)] = []
        for type in originalTypes {
            if let data = pasteboard.data(forType: type) {
                saved.append((type, data))
            }
        }

        pasteboard.clearContents()
        var declaredTypes = originalTypes
        if !declaredTypes.contains(.string) {
            declaredTypes.append(.string)
        }
        pasteboard.declareTypes(declaredTypes, owner: nil)
        for (type, data) in saved {
            pasteboard.setData(data, forType: type)
        }
        pasteboard.setString(string, forType: .string)
    }

    /// Read whatever's currently on the pasteboard and turn it into a
    /// `ClipboardItem`. Honors the community-standard NSPasteboard privacy
    /// markers used by password managers and transient generators.
    private func snapshot() -> ClipboardItem? {
        let types = Set(pasteboard.types ?? [])

        let concealed  = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
        let transient  = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
        let autogen    = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        if types.contains(concealed) || types.contains(transient) || types.contains(autogen) {
            return nil
        }

        // File URLs first — they often co-exist with a text representation
        // we don't want to mis-capture.
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self],
                                             options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return .fileURLs(urls)
        }

        // Image
        if types.contains(.tiff) || types.contains(.png),
           let img = NSImage(pasteboard: pasteboard),
           let tiff = img.tiffRepresentation,
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            let width = rep.pixelsWide > 0 ? rep.pixelsWide : Int(img.size.width)
            let height = rep.pixelsHigh > 0 ? rep.pixelsHigh : Int(img.size.height)
            return .image(pngData: png, width: width, height: height)
        }

        // RTF (preserves formatting)
        if let rtfData = pasteboard.data(forType: .rtf),
           let attr = try? NSAttributedString(
            data: rtfData,
            options: [.documentType: NSAttributedString.DocumentType.rtf],
            documentAttributes: nil
           ) {
            return .rtf(rtfData: rtfData, plain: attr.string)
        }

        // Plain text last
        if let s = pasteboard.string(forType: .string), !s.isEmpty {
            return .text(s)
        }

        return nil
    }
}
