import AppKit
import MultipasteCore

/// Polls `NSPasteboard.general.changeCount` and snapshots its contents into
/// the history store whenever the count advances.
///
/// macOS does not deliver KVO/notification for pasteboard mutations, so a
/// short interval poll is the canonical approach (this is what every macOS
/// clipboard manager does — Maccy, Paste, Alfred, etc.). 300ms strikes a
/// balance between snappy capture and near-zero CPU at idle.
final class ClipboardMonitor {

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: DispatchSourceTimer?
    private let store: HistoryStore

    /// When true, the monitor still tracks `changeCount` (so it doesn't
    /// double-fire on resume) but skips inserting into history.
    var paused: Bool = false

    init(store: HistoryStore) {
        self.store = store
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        let t = DispatchSource.makeTimerSource(queue: .main)
        t.schedule(deadline: .now() + .milliseconds(300), repeating: .milliseconds(300))
        t.setEventHandler { [weak self] in self?.poll() }
        t.resume()
        timer = t
    }

    func stop() {
        timer?.cancel()
        timer = nil
    }

    private func poll() {
        let cc = pasteboard.changeCount
        guard cc != lastChangeCount else { return }
        lastChangeCount = cc
        guard !paused else { return }
        guard let item = snapshot() else { return }
        store.insert(item)
    }

    /// Read whatever's currently on the pasteboard and turn it into a
    /// `ClipboardItem`. Honors the community-standard NSPasteboard privacy
    /// markers used by password managers and transient generators.
    private func snapshot() -> ClipboardItem? {
        let types = Set(pasteboard.types ?? [])

        let concealed  = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
        let transient  = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
        let autogen    = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        if types.contains(concealed) || types.contains(transient) || types.contains(autogen) {
            return nil
        }

        // File URLs first — they often co-exist with a text representation
        // we don't want to mis-capture.
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self],
                                             options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return .fileURLs(urls)
        }

        // Image
        if types.contains(.tiff) || types.contains(.png),
           let img = NSImage(pasteboard: pasteboard),
           let tiff = img.tiffRepresentation,
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            let width = rep.pixelsWide > 0 ? rep.pixelsWide : Int(img.size.width)
            let height = rep.pixelsHigh > 0 ? rep.pixelsHigh : Int(img.size.height)
            return .image(pngData: png, width: width, height: height)
        }

        // RTF (preserves formatting)
        if let rtfData = pasteboard.data(forType: .rtf),
           let attr = try? NSAttributedString(
            data: rtfData,
            options: [.documentType: NSAttributedString.DocumentType.rtf],
            documentAttributes: nil
           ) {
            return .rtf(rtfData: rtfData, plain: attr.string)
        }

        // Plain text last
        if let s = pasteboard.string(forType: .string), !s.isEmpty {
            return .text(s)
        }

        return nil
    }
}
